name: Node.js CI

on:
  push:
    branches: [ main ]       # Запуск при пуше в main
  pull_request:
    branches: [ main ]       # Запуск при PR

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build client
      run: npm run build

    - name: Run server (optional)
      run: npm run start:server